name: todo_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.4
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Kalam
      fonts:
        - asset: fonts/Kalam-Regular.ttf
        - asset: fonts/Kalam-Bold.ttf
          weight: 700
        - asset: fonts/Kalam-Light.ttf
          style: italic
